#include "spistresci.c"
void gra();
void load();
void menu();
void wstep();
void poruszaniesie();
void stats();
void mapa();
void poruszaniesie2();
void misje();
void ladowanie1();
void poruszaniesie3();
void walka();
void poruszaniesie4();
void poruszaniesie5();
void poruszaniesie6();
void poruszaniesie7();
void poruszaniesie8();
void poruszaniesie9();